### ISSUE TITLE
cannot import name 'LIBRARY_PATH' 

### ISSUE THREAD

**Issue by RicoFramboise** [juergenpabel/kalliope_trigger_porcupine2#1]
Hello,

I am trying to use porcupine V2.2 with kalliope. 
When I using porcupine2 I have this error code:
`File "resources/trigger/porcupine2/porcupine2.py", line 9, in <module>
    from pvporcupine import Porcupine, create as new_Porcupine, LIBRARY_PATH, MODEL_PATH
ImportError: cannot import name 'LIBRARY_PATH' from 'pvporcupine' (/usr/local/lib/python3.9/dist-packages/pvporcupine/__init__.py)`

I copied git folders into the Kalliope source file (onto trigger) and I changed settings.yml file.

How can I  use it correctly? (PS: I'm beginner on raspberry, sorry)

Thank you for your help

**Comment by juergenpabel** [comment]
It looks like LIBRARY_PATH and MODEL_PATH were removed from the pvporcupine library in version 2.2. I will investigate later on (or tomorrow) and change the implementation accordingly.

Meanwhile, you can try downgrading your pvporcupine to 2.1 (for debian/ubuntu based systems):
`sudo pip install pvporcupine==2.1`

**Comment by RicoFramboise** [comment]
Great, thanks.
Now I have an issue with access_key,  I write key in settings.yml file but it doesn't work.
It's look like:
```
triggers:
  - porcupine2:
      keywords:  
        - keyword: 
            ppn_file: "trigger/Jarvis_raspberry-pi_v2_2_0.ppn"
            sensitivity: 0.4
            access_key: "<Access_key>"
```

I try to find this issue :)
